### ISSUE TITLE
Add hint address support to signature scans

### ISSUE THREAD

**Issue by RagdollClash** [Sajidur78/CommonLoader#3]
Something that is done with Project Diva modding are hint addresses for signature scans. These immensely help with boot times, and would be able to give a purpose to the addresses that we add as comments for codes.

References:
 - https://github.com/blueskythlikesclouds/DivaModLoader/commit/7fd803e1097820585a42bdf43824a1f025cd6c44
 - https://github.com/ActualMandM/DivaDllMods/commit/14dd803501f2816cdd0137a001ba4f644029daf6

**Comment by Sajidur78** [comment]
We don't need hint address support anymore with the addition of signature caching in cb2892a.
